export const songs = [
  {
    id: 3,
    title: " Piel Canela",
    artist: "Cuco",
    url: "/media/meimportastu.mp3",
    lyrics: [
      { time: 0, text: "[..]" },
      { time: 16.48, text: "Que se quede el infinito sin estrellas" },
      { time: 20.84, text: "O que pierda el ancho más su intensidad" },
      { time: 24.98, text: "Pero el negro de tus ojos que no muera" },
      { time: 29.0, text: "Y el canela de tu piel se quede igual." },
      { time: 33.33, text: "Si perdiera el arco iris, su belleza" },
      { time: 37.0, text: "Y las flores, su perfume y su color." },
      { time: 41.68, text: "No sería tan inmensa mi tristeza" },
      { time: 45.24, text: "Como aquella de quererme sin tu amor." },
      { time: 49.04, text: "Me importas tú, y tú, y tú." },
      { time: 53.6, text: "Solamente tú, y tú, y tú." },
      { time: 56.96, text: "Me importas tú, y tú, y tú." },
      { time: 61.56, text: "Nadie más que tú." },
      { time: 65.22, text: "Me importas tú, y tú, y tú." },
      { time: 70.0, text: "Solamente tú, y tú, y tú." },
      { time: 73.64, text: "Me importas tú, y tú, y tú." },
      { time: 78.0, text: "Nadie más que tú." },
    ],
  },
  {
    id: 4,
    title: "Rock That Body",
    artist: "Black Eyed Peas",
    url: "/media/rockbody.mp3",
    lyrics: [
      { time: 0, text: "[..]" },
      { time: 5.0, text: "I wanna da -" },
      { time: 5.9, text: "I wanna dance in the lights" },
      { time: 9, text: "I wanna ro -" },
      { time: 10.4, text: "I wanna rock your body" },
      { time: 13.2, text: "I wanna go -" },
      { time: 14, text: "I wanna go for a ride" },
      { time: 16.82, text: "Hop in the music and" },
      { time: 18.22, text: "Rock your body" },
      { time: 20.58, text: "Rock that body" },
      { time: 21.58, text: "come on, come on" },
      { time: 22.58, text: "Rock that body" },

      { time: 23.52, text: "ROCK YOUR BODY" },

      { time: 24.22, text: "Rock that body" },
      { time: 25.52, text: "come on, come on" },
      { time: 26.52, text: "Rock that body" },
    ],
  },
  {
    id: 2,
    title: "I Wanna Be Yours",
    artist: "Arctic Monkeys",
    url: "/media/iwannabeyours.mp3",
    lyrics: [
      { time: 0, text: "[..]" },
      { time: 18, text: "I wanna be your vacuum cleaner" },
      { time: 21.7, text: "Breathing in your dust" },
      { time: 25, text: "I wanna be your Ford Cortina" },
      { time: 28, text: "I will never rust" },
      { time: 32, text: "If you like your coffee hot" },
      { time: 36, text: "Let me be your coffee pot" },
      { time: 39, text: "You call the shots, babe" },
      { time: 42, text: "I just wanna be yours" },
      { time: 46, text: "Secrets I have held in my heart" },
      { time: 50, text: "Are harder to hide than I thought" },
      { time: 53, text: "Maybe I just wanna be yours" },
      { time: 57, text: "I wanna be yours" },
      { time: 59, text: "I wanna be yours" },
      { time: 62, text: "I wanna be yours" },
      { time: 66, text: "I wanna be yours" },
      { time: 69, text: "I wanna be yours" },
      { time: 75, text: "Let me be your leccy meter" },
      { time: 78, text: "And I'll never run out" },
      { time: 81, text: "Let me be the portable heater" },
      { time: 85, text: "That you'll get cold without" },
      { time: 89, text: "I wanna be your setting lotion (wanna be)" },
      { time: 92, text: "Hold your hair in deep devotion (How deep?)" },
      { time: 96, text: "At least as deep as the Pacific Ocean" },
      { time: 100, text: "Now I wanna be yours" },
      { time: 103, text: "Secrets I have held in my heart" },
      { time: 107, text: "Are harder to hide than I thought" },
      { time: 111, text: "Maybe I just wanna be yours" },
      { time: 115, text: "I wanna be yours" },
      { time: 118, text: "Wanna be yours" },
      { time: 122, text: "Wanna be yours" },
      { time: 126, text: "Wanna be yours" },
      { time: 129, text: "Wanna be yours" },
      { time: 132, text: "Wanna be yours" },
      { time: 137, text: "Wanna be yours" },
      { time: 140, text: "Wanna be yours" },
      { time: 145, text: "Wanna be yours" },
      { time: 148, text: "I want to be yours" },
      { time: 151, text: "I want to be along" },
      { time: 155, text: "I want to be yours" },
      { time: 158, text: "I want to be yours" },
      { time: 161, text: "I want to be yours" },
      { time: 164, text: "I want to be yours" },
      { time: 168, text: "I want to be yours" },
      { time: 174, text: "I want to be yours" },
    ],
  },
  {
    id: 1,
    title: "JVKE ",
    artist: "Arctic Monkeys",
    url: "/media/JVKE.mp3",
    lyrics: [
      { time: 0, text: "[..]" },
      { time: 39.55, text: "FEEL LIKE SUNN" },
      { time: 41.95, text: "ON MY SKINN" },
      { time: 44.21, text: "SO THIS IS LOVEEE" },
      { time: 46.61, text: "I KNOW IT ISSS " },
      { time: 48.38, text: "I know I sound super cliché" },
      { time: 50.78, text: "But you make me feel some type of way" },
      { time: 52.62, text: "This is falling, falling in love" },
      { time: 64.22, text: "I got a lot on my mind" },
      { time: 65.8, text: "Got some more on my plate" },
      {
        time: 68.02,
        text: "My baby got me looking forward to the end of the day",
      },
      { time: 71.54, text: "What you say?" },
      { time: 73.54, text: "You and me?" },
      {
        time: 74.97,
        text: "Just forget about the past, throw it in the trash",
      },
      { time: 79.26, text: "What you say?" },
      { time: 81.26, text: "You and me?" },
      {
        time: 82.83,
        text: "Live the life we never had, like we're never going back",
      },
      { time: 90.82, text: "FEEL LIKE SUNN" },
      { time: 92.82, text: "ON MY SKINN" },
      { time: 94.78, text: "SO THIS IS LOVEEE" },
      { time: 96.78, text: "I KNOW IT ISSS " },
      { time: 98.8, text: "I know I sound super cliché" },
      { time: 101.1, text: "But you make me feel some type of way" },
      { time: 103.23, text: "This is falling, falling in love" },
      { time: 107.46, text: "I know I sound super cliché" },
      { time: 108.96, text: "But you make me feel some type of way" },
      { time: 111.79, text: "This is falling, falling in love..." },
      { time: 118.23, text: "Yeah" },
      { time: 120.28, text: "This is falling, falling in love" },
      { time: 124.69, text: "Ooh..." },
      { time: 129.17, text: "This is falling, falling in love" },
      { time: 134.4, text: "" },
    ],
  },
      {
    id: 5,
    title: "Yung Kai ",
    artist: "Blue",
    url: "/media/blue.mp3",
    lyrics: [
      { time: 18.5, text: "Your morning eyes" },
      { time: 21.2, text: "I could stare like watching stars" },
      { time: 26.1, text: "I could walk you by" },
      { time: 28.9, text: "And I'll tell without a thought" },
      { time: 32.1, text: "You'd be mine" },
      { time: 34.1, text: "Would you mind" },
      { time: 36.1, text: "if I took your hand tonight?" },
      { time: 39.7, text: "Know you're" },
      { time: 41.7, text: "that I want," },
      { time: 43.9, text: "it's fine" },
      { time: 47.5, text: "I imagine we fell in love" },
      { time: 50.5, text: "A love under moonlight skies with you" },
      { time: 54.2, text: "I think I'll picture us here with the waves" },
      { time: 57.7, text: "The ocean's colors on your face" },
      { time: 61.3, text: "I'll leave my heart with your air" },
      { time: 65.4, text: "So let me fly with you" },
      { time: 68.8, text: "Will you be forever with me?" },
      
      { time: 106.7, text: "You're my favorite place" },
      { time: 110.1, text: "So always I will stay" },
      { time: 114.1, text: "The look that's on your face" },
      { time: 117.7, text: "I think you feel the same" },
      { time: 121.1, text: "Fate is on us, you'll be my muse" },
      { time: 124.9, text: "I love you, I love you, I love you, I do" },
      { time: 128.2, text: "If you are the ocean then I am the blue" },
      { time: 132.1, text: "I love you, I love you, I love you, I do" },
      { time: 135.8, text: "I imagine we fell in love" },
      { time: 139.0, text: "A love under moonlight skies with you" },
      { time: 142.5, text: "I think I'll picture us here with the waves" },
      { time: 146.4, text: "The ocean's colors on your face" },
      { time: 149.8, text: "I'll leave my heart with your air" },
      { time: 154.5, text: "So let me fly with you" },
      { time: 157.5, text: "Will you be forever with me?" },
    ],
  },
];
