export const songs = [
  {
    id: 3,
    title: "Piel Canela",
    artist: "Cuco",
    url: "/media/meimportastu.mp3",
    lyrics: [
      { time: 0, text: "[..]", translation: "[..]" },
      { time: 16.48, text: "Que se quede el infinito sin estrellas", translation: "Sonsuzluk yıldızlarını kaybetsin" },
      { time: 20.84, text: "O que pierda el ancho más su intensidad", translation: "Ya da deniz genişliğini yitirsin" },
      { time: 24.98, text: "Pero el negro de tus ojos que no muera", translation: "Ama gözlerinin siyahı kaybolmasın" },
      { time: 29.0, text: "Y el canela de tu piel se quede igual.", translation: "Ve teninin tarçın rengi aynı kalsın" },
      { time: 33.33, text: "Si perdiera el arco iris, su belleza", translation: "Gökkuşağı güzelliğini kaybetse" },
      { time: 37.0, text: "Y las flores, su perfume y su color.", translation: "Ve çiçekler kokusunu ve rengini yitirse" },
      { time: 41.68, text: "No sería tan inmensa mi tristeza", translation: "Üzüntüm o kadar büyük olmazdı" },
      { time: 45.24, text: "Como aquella de quererme sin tu amor.", translation: "Sensiz sevgisiz beni sevmek kadar" },
      { time: 49.04, text: "Me importas tú, y tú, y tú.", translation: "Sen önemlisin, sen, sen, sen" },
      { time: 53.6, text: "Solamente tú, y tú, y tú.", translation: "Sadece sen, ve sen, ve sen" },
      { time: 56.96, text: "Me importas tú, y tú, y tú.", translation: "Sen önemlisin, sen, sen, sen" },
      { time: 61.56, text: "Nadie más que tú.", translation: "Senden başkası değil" },
      { time: 65.22, text: "Me importas tú, y tú, y tú.", translation: "Sen önemlisin, sen, sen, sen" },
      { time: 70.0, text: "Solamente tú, y tú, y tú.", translation: "Sadece sen, ve sen, ve sen" },
      { time: 73.64, text: "Me importas tú, y tú, y tú.", translation: "Sen önemlisin, sen, sen, sen" },
      { time: 78.0, text: "Nadie más que tú.", translation: "Senden başkası değil" },
    ],
  },
  {
    id: 4,
    title: "Rock That Body",
    artist: "Black Eyed Peas",
    url: "/media/rockbody.mp3",
    lyrics: [
      { time: 0, text: "[..]", translation: "[..]" },
      { time: 5.0, text: "I wanna da -", translation: "Ben dans -" },
      { time: 5.9, text: "I wanna dance in the lights", translation: "Işıklarda dans etmek istiyorum" },
      { time: 9, text: "I wanna ro -", translation: "Ben salla -" },
      { time: 10.4, text: "I wanna rock your body", translation: "Vücudunu sallamak istiyorum" },
      { time: 13.2, text: "I wanna go -", translation: "Ben gitmek -" },
      { time: 14, text: "I wanna go for a ride", translation: "Bir tura çıkmak istiyorum" },
      { time: 16.82, text: "Hop in the music and", translation: "Müziğe atla ve" },
      { time: 18.22, text: "Rock your body", translation: "Vücudunu salla" },
      { time: 20.58, text: "Rock that body", translation: "O vücudu salla" },
      { time: 21.58, text: "come on, come on", translation: "hadi, hadi" },
      { time: 22.58, text: "Rock that body", translation: "O vücudu salla" },
      { time: 23.52, text: "ROCK YOUR BODY", translation: "VÜCUDUNU SALLA" },
      { time: 24.22, text: "Rock that body", translation: "O vücudu salla" },
      { time: 25.52, text: "come on, come on", translation: "hadi, hadi" },
      { time: 26.52, text: "Rock that body", translation: "O vücudu salla" },
    ],
  },
  {
    id: 2,
    title: "I Wanna Be Yours",
    artist: "Arctic Monkeys",
    url: "/media/iwannabeyours.mp3",
    lyrics: [
      { time: 0, text: "[..]", translation: "[..]" },
      { time: 18, text: "I wanna be your vacuum cleaner", translation: "Senin elektrik süpürgen olmak istiyorum" },
      { time: 21.7, text: "Breathing in your dust", translation: "Tozunu içime çekerek" },
      { time: 25, text: "I wanna be your Ford Cortina", translation: "Senin Ford Cortina'n olmak istiyorum" },
      { time: 28, text: "I will never rust", translation: "Asla paslanmayacağım" },
      { time: 32, text: "If you like your coffee hot", translation: "Eğer kahveni sıcak seversen" },
      { time: 36, text: "Let me be your coffee pot", translation: "Senin kahve makinan olayım" },
      { time: 39, text: "You call the shots, babe", translation: "Sen karar ver bebeğim" },
      { time: 42, text: "I just wanna be yours", translation: "Sadece senin olmak istiyorum" },
      { time: 46, text: "Secrets I have held in my heart", translation: "Kalbimde sakladığım sırlar" },
      { time: 50, text: "Are harder to hide than I thought", translation: "Düşündüğümden daha zor saklanıyor" },
      { time: 53, text: "Maybe I just wanna be yours", translation: "Belki sadece senin olmak istiyorum" },
      { time: 57, text: "I wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 59, text: "I wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 62, text: "I wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 66, text: "I wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 69, text: "I wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 75, text: "Let me be your leccy meter", translation: "Senin elektrik sayacın olayım" },
      { time: 78, text: "And I'll never run out", translation: "Ve asla bitmeyeceğim" },
      { time: 81, text: "Let me be the portable heater", translation: "Senin taşınabilir ısıtıcın olayım" },
      { time: 85, text: "That you'll get cold without", translation: "Onsuz üşüyeceğin" },
      { time: 89, text: "I wanna be your setting lotion (wanna be)", translation: "Senin saç losyonun olmak istiyorum" },
      { time: 92, text: "Hold your hair in deep devotion (How deep?)", translation: "Saçını derin bağlılıkla tutmak" },
      { time: 96, text: "At least as deep as the Pacific Ocean", translation: "En azından Pasifik Okyanusu kadar derin" },
      { time: 100, text: "Now I wanna be yours", translation: "Şimdi senin olmak istiyorum" },
      { time: 103, text: "Secrets I have held in my heart", translation: "Kalbimde sakladığım sırlar" },
      { time: 107, text: "Are harder to hide than I thought", translation: "Düşündüğümden daha zor saklanıyor" },
      { time: 111, text: "Maybe I just wanna be yours", translation: "Belki sadece senin olmak istiyorum" },
      { time: 115, text: "I wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 118, text: "Wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 122, text: "Wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 126, text: "Wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 129, text: "Wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 132, text: "Wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 137, text: "Wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 140, text: "Wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 145, text: "Wanna be yours", translation: "Senin olmak istiyorum" },
      { time: 148, text: "I want to be yours", translation: "Senin olmak istiyorum" },
      { time: 151, text: "I want to be along", translation: "Seninle olmak istiyorum" },
      { time: 155, text: "I want to be yours", translation: "Senin olmak istiyorum" },
      { time: 158, text: "I want to be yours", translation: "Senin olmak istiyorum" },
      { time: 161, text: "I want to be yours", translation: "Senin olmak istiyorum" },
      { time: 164, text: "I want to be yours", translation: "Senin olmak istiyorum" },
      { time: 168, text: "I want to be yours", translation: "Senin olmak istiyorum" },
      { time: 174, text: "I want to be yours", translation: "Senin olmak istiyorum" },
    ],
  },
  {
    id: 1,
    title: "JVKE",
    artist: "Arctic Monkeys",
    url: "/media/JVKE.mp3",
    lyrics: [
      { time: 0, text: "[..]", translation: "[..]" },
      { time: 39.55, text: "FEEL LIKE SUNN", translation: "GÜNEŞ GİBİ" },
      { time: 41.95, text: "ON MY SKINN", translation: "TENİMDE" },
      { time: 44.21, text: "SO THIS IS LOVEEE", translation: "BU AŞK DEMEK" },
      { time: 46.61, text: "I KNOW IT ISSS", translation: "BİLİYORUM ÖYLE" },
      { time: 48.38, text: "I know I sound super cliché", translation: "Çok klişe geldiğimi biliyorum" },
      { time: 50.78, text: "But you make me feel some type of way", translation: "Ama bana farklı hissettiriyorsun" },
      { time: 52.62, text: "This is falling, falling in love", translation: "Bu aşka düşmek, aşka düşmek" },
      { time: 64.22, text: "I got a lot on my mind", translation: "Aklımda çok şey var" },
      { time: 65.8, text: "Got some more on my plate", translation: "Tabağımda daha fazlası var" },
      { time: 68.02, text: "My baby got me looking forward to the end of the day", translation: "Bebeğim günün sonunu beklememi sağlıyor" },
      { time: 71.54, text: "What you say?", translation: "Ne diyorsun?" },
      { time: 73.54, text: "You and me?", translation: "Sen ve ben?" },
      { time: 74.97, text: "Just forget about the past, throw it in the trash", translation: "Geçmişi unut, çöpe at" },
      { time: 79.26, text: "What you say?", translation: "Ne diyorsun?" },
      { time: 81.26, text: "You and me?", translation: "Sen ve ben?" },
      { time: 82.83, text: "Live the life we never had, like we're never going back", translation: "Hiç yaşamadığımız hayatı yaşa, asla geri dönmeyecekmiş gibi" },
      { time: 90.82, text: "FEEL LIKE SUNN", translation: "GÜNEŞ GİBİ" },
      { time: 92.82, text: "ON MY SKINN", translation: "TENİMDE" },
      { time: 94.78, text: "SO THIS IS LOVEEE", translation: "BU AŞK DEMEK" },
      { time: 96.78, text: "I KNOW IT ISSS", translation: "BİLİYORUM ÖYLE" },
      { time: 98.8, text: "I know I sound super cliché", translation: "Çok klişe geldiğimi biliyorum" },
      { time: 101.1, text: "But you make me feel some type of way", translation: "Ama bana farklı hissettiriyorsun" },
      { time: 103.23, text: "This is falling, falling in love", translation: "Bu aşka düşmek, aşka düşmek" },
      { time: 107.46, text: "I know I sound super cliché", translation: "Çok klişe geldiğimi biliyorum" },
      { time: 108.96, text: "But you make me feel some type of way", translation: "Ama bana farklı hissettiriyorsun" },
      { time: 111.79, text: "This is falling, falling in love...", translation: "Bu aşka düşmek, aşka düşmek..." },
      { time: 118.23, text: "Yeah", translation: "Evet" },
      { time: 120.28, text: "This is falling, falling in love", translation: "Bu aşka düşmek, aşka düşmek" },
      { time: 124.69, text: "Ooh...", translation: "Ooh..." },
      { time: 129.17, text: "This is falling, falling in love", translation: "Bu aşka düşmek, aşka düşmek" },
      { time: 134.4, text: "", translation: "" },
    ],
  },
  {
    id: 5,
    title: "Yung Kai",
    artist: "Blue",
    url: "/media/blue.mp3",
    lyrics: [
      { time: 0, text: "[..]", translation: "[..]" },
      { time: 18.5, text: "Your morning eyes", translation: "Sabah gözlerin" },
      { time: 21.2, text: "I could stare like watching stars", translation: "Yıldızlara bakar gibi bakabilirim" },
      { time: 26.1, text: "I could walk you by", translation: "Yanından geçebilirim" },
      { time: 28.9, text: "And I'll tell without a thought", translation: "Ve düşünmeden söylerim" },
      { time: 32.1, text: "You'd be mine", translation: "Benim olurdun" },
      { time: 34.1, text: "Would you mind", translation: "Sakıncası var mı" },
      { time: 36.1, text: "If I took your hand tonight?", translation: "Bu gece elini tutsam?" },
      { time: 39.7, text: "Know you're", translation: "Biliyorum sen" },
      { time: 41.7, text: "That I want,", translation: "Istediğim kişisin," },
      { time: 43.9, text: "This life", translation: "Bu hayat" },
      { time: 47.5, text: "I imagine we fell in love", translation: "Aşık olduğumuzu hayal ediyorum" },
      { time: 50.5, text: "I'll nap under moonlight skies with you", translation: "Ay ışığı altında seninle birlikte bir şekerleme yapacağım." },
      { time: 54.2, text: "I think I'll picture us, you with the waves", translation: "Sanırım bizi, seni dalgalarla birlikte hayal edeceğim." },
      { time: 57.7, text: "The ocean's colors on your face", translation: "Yüzünde okyanusun renkleri" },
      { time: 61.3, text: "I'll leave my heart with your air", translation: "Kalbimi senin havanla bırakacağım" },
      { time: 65.4, text: "So let me fly with you", translation: "O yüzden seninle uçmama izin ver" },
      { time: 68.8, text: "Will you be forever with me?", translation: "Sonsuza dek benimle olacak mısın?" },
      { time: 106.7, text: "You're my favorite place", translation: "Sen benim en sevdiğim yerimsin" },
      { time: 110.1, text: "So always I will stay", translation: "Bu yüzden her zaman kalacağım" },
      { time: 114.1, text: "The look that's on your face", translation: "Yüzündeki o bakış" },
      { time: 117.7, text: "I think you feel the same", translation: "Sanırım sen de aynısını hissediyorsun" },
      { time: 121.1, text: "Fate is on us, you'll be my muse", translation: "Kader bizden yana, sen benim ilham kaynağım olacaksın" },
      { time: 124.9, text: "I love you, I love you, I love you, I do", translation: "Seni seviyorum, seni seviyorum, seni seviyorum, seviyorum" },
      { time: 128.2, text: "If you are the ocean then I am the blue", translation: "Eğer sen okyanussan o zaman ben maviyim" },
      { time: 132.1, text: "I love you, I love you, I love you, I do", translation: "Seni seviyorum, seni seviyorum, seni seviyorum, seviyorum" },
      { time: 135.8, text: "I imagine we fell in love", translation: "Aşık olduğumuzu hayal ediyorum" },
      { time: 139.0, text: "A love under moonlight skies with you", translation: "Seninle ay ışığı altında bir aşk" },
      { time: 142.5, text: "I think I'll picture us here with the waves", translation: "Sanırım bizi burada dalgalarla hayal edeceğim" },
      { time: 146.4, text: "The ocean's colors on your face", translation: "Yüzünde okyanusun renkleri" },
      { time: 149.8, text: "I'll leave my heart with your air", translation: "Kalbimi senin havanla bırakacağım" },
      { time: 154.5, text: "So let me fly with you", translation: "O yüzden seninle uçmama izin ver" },
      { time: 157.5, text: "Will you be forever with me?", translation: "Sonsuza dek benimle olacak mısın?" },
    ],
  },
];